# Tensorflow


In [1]:
import tensorflow as tf # type: ignore
import numpy as np

# Tensor
In the context of data science, tensors are multi-dimensional arrays of numbers that represent complex data. They are the fundamental data structures used in machine learning and deep learning frameworks like TensorFlow and PyTorch.


<img src="./Images/DimentionalImg.png" width=800>

# 1D & 2D Tensor

#### Initialization of Tensor

In [2]:
#In other words Creating an tensor in creating an matrix

x = tf.constant([[2,3,4],[3,4,5]],shape=(2,3),dtype=tf.int32)

print(x)

tf.Tensor(
[[2 3 4]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [3]:
# Creating matrix/tensor of ones with specific dimention and datatype 

x = tf.ones((3,3), dtype=tf.int32 )

print(x)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [7]:
# Creating matrix/tensor of zeros with specific dimention and datatype 


x = tf.zeros((3,3), dtype=tf.float32 )
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [8]:
# Creating matrix/tensor of random values with specific dimention and datatype 

x = tf.random.normal((3,3),mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.86109746 -1.6804336  -1.4363093 ]
 [-1.1378163  -1.4825509   2.0929785 ]
 [ 0.11069465 -0.7074017   0.36067188]], shape=(3, 3), dtype=float32)


#### Mathematical Operation 

In [13]:
# Sone mathematical operations on the created matrix

x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x,y)
print(z)

k = tf.subtract(x,y)
print(k)

l = tf.divide(x,y)
print(l)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [12]:
# Matrix Multiplication

x = tf.random.normal((3,3))
y = tf.random.normal((3,3))

z = tf.matmul(x,y)
print(x)
print(y)
print(z)

tf.Tensor(
[[ 1.4435412   0.5120111  -0.7610575 ]
 [-1.0564437  -0.3095165   0.33338532]
 [-0.52584386 -0.35301808 -1.4553332 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.3138072   0.17399165  0.56398606]
 [-2.0593479   0.5096774   0.92672265]
 [-0.6954625   0.87199867  0.13124304]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.3714128  -0.15151653  1.188746  ]
 [-0.9824183  -0.05085438 -0.838901  ]
 [ 1.0482593  -1.5404664  -0.8147208 ]], shape=(3, 3), dtype=float32)


## 2D Tensor Indexing 

In [16]:

# Mostly similar to the pandas indexing of the multidimentional array
# ""   (x[start,stop,steps])  ""

x = tf.constant([0,1,2,3,4,5,6,7,8,9,10])
print(x[:])
print(x[1:6])

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10], shape=(11,), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [19]:
# Taking some specific values from other matrix

x = tf.constant([0,1,2,3,4,5,7,8,9,10])

indices = tf.constant([0,7])

x_ind = tf.gather(x,indices)

print(x_ind)

tf.Tensor([0 8], shape=(2,), dtype=int32)


In [6]:
g = tf.constant([[2,3,4],[3,4,5],[2,4,5]])

In [7]:
print(g)

tf.Tensor(
[[2 3 4]
 [3 4 5]
 [2 4 5]], shape=(3, 3), dtype=int32)


In [11]:
# Indexing in 2D

print(g[1:2,1:3])



tf.Tensor([[4 5]], shape=(1, 2), dtype=int32)


#### Reshaping 

In [21]:
# Original matirix
x = tf.range(9)
print(x)

# Reshaped matrix
y = tf.reshape(x, (3,3))
print(y)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


# 3D Tensor


In [25]:
# In other words Creating an tensor in creating an matrix
a = tf.constant([[[2,3,4],[3,4,5]],[[4,5,6],[4,5,6]]])

In [26]:
print(a)

tf.Tensor(
[[[2 3 4]
  [3 4 5]]

 [[4 5 6]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)


In [29]:
a.shape

TensorShape([2, 2, 3])

In [40]:
# Creating matrix/tensor of ones with specific dimention and datatype 
y = tf.ones((2,2,3), dtype=tf.int32 )

In [41]:
print(y)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]], shape=(2, 2, 3), dtype=int32)


## 3D Tensor Indexing 

In [12]:
t = tf.constant([[[2,3,4],[3,4,5]],[[4,5,6],[4,5,6]]])
print(t)

tf.Tensor(
[[[2 3 4]
  [3 4 5]]

 [[4 5 6]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)


In [24]:
# Indexting in 3d tensor

print(t[0:2,0:3,0:3])

tf.Tensor(
[[[2 3 4]
  [3 4 5]]

 [[4 5 6]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)


# 4D Tensor

In [32]:
b = tf.constant([[[[2,3,4],[3,4,5]],[[2,4,5],[4,5,6]],[[3,8,9],[6,7,8]]],[[[2,3,4],[3,4,5]],[[2,4,5],[4,5,6]],[[3,8,9],[6,7,8]]]])

In [33]:
print(b)

tf.Tensor(
[[[[2 3 4]
   [3 4 5]]

  [[2 4 5]
   [4 5 6]]

  [[3 8 9]
   [6 7 8]]]


 [[[2 3 4]
   [3 4 5]]

  [[2 4 5]
   [4 5 6]]

  [[3 8 9]
   [6 7 8]]]], shape=(2, 3, 2, 3), dtype=int32)


In [38]:
# Creating matrix/tensor of ones with specific dimention and datatype 
c = tf.ones((2,3,2,3), dtype=tf.int32 )

In [39]:
print(c)

tf.Tensor(
[[[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]], shape=(2, 3, 2, 3), dtype=int32)


# Operations

In [4]:
# Converting an numpy arry into tensor

np_array = np.array([1,2,3,4])

print(np_array)

converted_tensor = tf.convert_to_tensor(np_array)

print(converted_tensor)


[1 2 3 4]
tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


In [15]:
# It Construct an identity matrix, or a batch of matrices.


eye_tensor = tf.eye(
    num_rows= 3,
    num_columns=4,
    batch_shape=[1,2,3], # Defines the shape/Dimention of the array
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)

tf.Tensor(
[[[[[1. 0. 0. 0.]
    [0. 1. 0. 0.]
    [0. 0. 1. 0.]]

   [[1. 0. 0. 0.]
    [0. 1. 0. 0.]
    [0. 0. 1. 0.]]

   [[1. 0. 0. 0.]
    [0. 1. 0. 0.]
    [0. 0. 1. 0.]]]


  [[[1. 0. 0. 0.]
    [0. 1. 0. 0.]
    [0. 0. 1. 0.]]

   [[1. 0. 0. 0.]
    [0. 1. 0. 0.]
    [0. 0. 1. 0.]]

   [[1. 0. 0. 0.]
    [0. 1. 0. 0.]
    [0. 0. 1. 0.]]]]], shape=(1, 2, 3, 3, 4), dtype=float32)


In [25]:
# It Creates a tensor filled with a scalar value.

# tf.fill( dims, value, name=None, layout=None)

fill_tensor = tf.fill([2,4,3],6) 

print(fill_tensor)
 

tf.Tensor(
[[[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]], shape=(2, 4, 3), dtype=int32)
