# Tensorflow


In [1]:
import tensorflow as tf

## Tensor
In the context of data science, tensors are multi-dimensional arrays of numbers that represent complex data. They are the fundamental data structures used in machine learning and deep learning frameworks like TensorFlow and PyTorch.


#### Initialization of Tensor

In [2]:
#In other words Creating an tensor in creating an matrix

x = tf.constant([[2,3,4],[3,4,5]],shape=(2,3),dtype=tf.int32)

print(x)

tf.Tensor(
[[2 3 4]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [3]:
# Creating matrix/tensor of ones with specific dimention and datatype 

x = tf.ones((3,3), dtype=tf.int32 )

print(x)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


In [7]:
# Creating matrix/tensor of zeros with specific dimention and datatype 


x = tf.zeros((3,3), dtype=tf.float32 )
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [8]:
# Creating matrix/tensor of random values with specific dimention and datatype 

x = tf.random.normal((3,3),mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.86109746 -1.6804336  -1.4363093 ]
 [-1.1378163  -1.4825509   2.0929785 ]
 [ 0.11069465 -0.7074017   0.36067188]], shape=(3, 3), dtype=float32)


## Mathematical Operation 

In [13]:
# Sone mathematical operations on the created matrix

x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x,y)
print(z)

k = tf.subtract(x,y)
print(k)

l = tf.divide(x,y)
print(l)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [12]:
# Matrix Multiplication

x = tf.random.normal((3,3))
y = tf.random.normal((3,3))

z = tf.matmul(x,y)
print(x)
print(y)
print(z)

tf.Tensor(
[[ 1.4435412   0.5120111  -0.7610575 ]
 [-1.0564437  -0.3095165   0.33338532]
 [-0.52584386 -0.35301808 -1.4553332 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.3138072   0.17399165  0.56398606]
 [-2.0593479   0.5096774   0.92672265]
 [-0.6954625   0.87199867  0.13124304]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.3714128  -0.15151653  1.188746  ]
 [-0.9824183  -0.05085438 -0.838901  ]
 [ 1.0482593  -1.5404664  -0.8147208 ]], shape=(3, 3), dtype=float32)


In [16]:
# Matrix Indexing
# Mostly similar to the pandas indexing of the multidimentional array
# ""   (x[start,stop,steps])  ""

x = tf.constant([0,1,2,3,4,5,6,7,8,9,10])
print(x[:])
print(x[1:6])

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10], shape=(11,), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [19]:
# Taking some specific values from other matrix

x = tf.constant([0,1,2,3,4,5,7,8,9,10])

indices = tf.constant([0,7])

x_ind = tf.gather(x,indices)

print(x_ind)

tf.Tensor([0 8], shape=(2,), dtype=int32)


## Reshaping 

In [21]:
# Original matirix
x = tf.range(9)
print(x)

# Reshaped matrix
y = tf.reshape(x, (3,3))
print(y)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
