In [2]:
import tensorflow as tf
import numpy as np

### Absolute value

In [6]:
# This function did't convert your actual tensor to absolute value bhut it convert so you can use it in other verable or other function
# Your original variable remain unchanges 

x_abs = tf.constant([-2.3,9.1])

tf.abs(x_abs)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.3, 9.1], dtype=float32)>

### Elementwise addition , division , substraction 

In [41]:
# The shape and type of the tensor should be same for mathematical operations

x_1 = tf.constant([1,2,3,4,5])
x_2 = tf.constant([5,4,3,2,1])

add = print(tf.math.add(x_1,x_2))

sub = print(tf.math.subtract(x_1,x_2))

div = print(tf.math.divide(x_1,x_2))

print(tf.math.divide_no_nan(x_1,x_2))

tf.Tensor([6 6 6 6 6], shape=(5,), dtype=int32)
tf.Tensor([-4 -2  0  2  4], shape=(5,), dtype=int32)
tf.Tensor([0.2 0.5 1.  2.  5. ], shape=(5,), dtype=float64)
tf.Tensor([0.2 0.5 1.  2.  5. ], shape=(5,), dtype=float64)


### Method is used to find the maximum value across the axes 

##### This shows the maximum value across the axes

def argmax( <br>
>>>input: Any,<br>
>>>axis: Any | None = None,<br>
>>>output_type: DType = dtypes.int64,<br>
>>>name: Any | None = None<br>

):


In [17]:
#  1D tensor:

# tf.Tensor(5, shape=(), dtype=int64) this is the output shows the position of the max value

x_argmax = tf.constant([1,2,3,4,5,6])

print(x_argmax)

print(tf.math.argmax(x_argmax))

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int64)


In [42]:
#  2D tensor

y_argmax = tf.constant([[2,4,53],[4,5,6],[4,5,7]])

print(y_argmax)

print(tf.math.argmax(y_argmax,1)) # 1 is the axis  

# AXIS 0 vvvvvv (default) 

# AXIS 1 >>>>>

tf.Tensor(
[[ 2  4 53]
 [ 4  5  6]
 [ 4  5  7]], shape=(3, 3), dtype=int32)
tf.Tensor([2 2 2], shape=(3,), dtype=int64)


### Elementwise equal Checker

Returns the truth value of (x == y) element-wise. <br>
Should be of same shape

In [37]:
# 1D tensor

X_equal = tf.constant([1,2,5,2])
Y_equal = tf.constant([1,2,5,2])

print(tf.math.equal(X_equal,Y_equal))


tf.Tensor([ True  True  True  True], shape=(4,), dtype=bool)


### Computes the power of one value to another

In [44]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)  # [[256, 65536], [9, 27]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

### Reduce Sum

It Basically Add all the element on the basisi of axis

axis = None  (Sum of all the elemnt) <br>
axis = 0     (Sum of all vvvvv)<br>
axis = 1     (Sum of all >>>>>)<br>

In [48]:

y = tf.constant([[2,4,53],[4,5,6],[4,5,7]])
print(y)


print(tf.math.reduce_sum(
    y, axis=0, keepdims=False, name=None
))

tf.Tensor(
[[ 2  4 53]
 [ 4  5  6]
 [ 4  5  7]], shape=(3, 3), dtype=int32)
tf.Tensor([10 14 66], shape=(3,), dtype=int32)


### Reduce Mean

Computes the mean of elements across dimensions of a tensor.

It Basically give mean on the basisi of axis

axis = None  (Mean of all the elemnt)<br>
axis = 0     (Mean of all vvvvv)<br>
axis = 1     (Mean of all >>>>>)<br>

In [58]:
y = tf.constant([[2,4,53],[4,5,6],[4,5,7]],dtype=tf.float32)
print(y)

print(tf.math.reduce_mean(
    y, axis=0, keepdims=False, name=None
))

tf.Tensor(
[[ 2.  4. 53.]
 [ 4.  5.  6.]
 [ 4.  5.  7.]], shape=(3, 3), dtype=float32)
tf.Tensor([ 3.3333333  4.6666665 22.       ], shape=(3,), dtype=float32)


### Standard deviation

Computes the standard deviation of elements across dimensions of a tensor.



In [57]:
y = tf.constant([[2,4,53],[4,5,6],[4,5,7]],dtype=tf.float32)
print(y)

print(tf.math.reduce_std(
    y, axis=None, keepdims=False, name=None
))

tf.Tensor(
[[ 2.  4. 53.]
 [ 4.  5.  6.]
 [ 4.  5.  7.]], shape=(3, 3), dtype=float32)
tf.Tensor(15.260697, shape=(), dtype=float32)


### TOP Function

Finds values and indices of the k largest entries for the last dimension.

This function go to each and every Row and find top_k values

In [62]:
# The second array in the output is the index of the top k value

y = tf.constant([[2,4,53],[4,5,6],[4,5,7]],dtype=tf.float32)
print(y)

print(tf.math.top_k(
    y,
    k=1,
    sorted=True,
    index_type=tf.dtypes.int32,
    name=None
))

tf.Tensor(
[[ 2.  4. 53.]
 [ 4.  5.  6.]
 [ 4.  5.  7.]], shape=(3, 3), dtype=float32)
TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[53.],
       [ 6.],
       [ 7.]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2]], dtype=int32)>)
